### ISSUE TITLE
Fix the 2021 Rochester Leaderboard to use local files

### ISSUE THREAD

**Issue by jobartucz** [Minnesota-Computer-Club/MCC-Website#1]
I changed index.js to use the local paths for the individual and team files. I don't want those to be publicly accessible in the future. 

all the data files will be stored in sub-folders of /var/www/private/AOC on the main server. 

@KennyHarrer , can you fix index.js to use these files now?

**Comment by KennyHarrer** [comment]
already in to-do list https://github.com/Minnesota-Computer-Club/MCC-Website/issues/3#issue-1463941836
