### ISSUE TITLE
Add 2 lists at bottom of leaderboards

### ISSUE THREAD

**Issue by jobartucz** [Minnesota-Computer-Club/MCC-Website#34]
list 1: people that have filled out google form but not joined any AOC leaderboard
list 2: people that have joined AOC leaderboard but not filled out Google Form

**Comment by jobartucz** [comment]
RPS: https://adventofcode.com/2022/leaderboard/private/view/641987
MN : https://adventofcode.com/2022/leaderboard/private/view/2216296

**Comment by cursorweb** [comment]
how can you track the number of stars for people who haven't joined the leaderboard for list 1?

**Comment by cursorweb** [comment]
pr #35

**Comment by cursorweb** [comment]
i'm going to close this
